version: '3.8'
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      DATABASE_URL: "postgres://postgres:postgres@db:5432/shahara"  # Changed to shahara
    command: ./entrypoint.sh
    volumes:
      - ./horilla:/app/horilla
      - app_static:/app/staticfiles  # Named volume for static files
      - app_media:/app/media  # Named volume for media files
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network

  db:
    image: postgres:16-bullseye
    environment:
      POSTGRES_DB: shahara  # Changed to shahara
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256"
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Named volume for database data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  nginx:
    image: nginx:latest
    ports:
      - "80:80"  # Expose port 80 for HTTP
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro  # Nginx configuration file
      - app_static:/app/staticfiles:ro  # Serve static files
      - app_media:/app/media:ro  # Serve media files
    depends_on:
      - server
    networks:
      - app-network

volumes:
  postgres_data:  # Volume for PostgreSQL data
  app_static:  # Volume for static files
  app_media:  # Volume for media files

networks:
  app-network:
    driver: bridge
